/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ProofLayerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorProof"
      | "getProof"
      | "proofCreator"
      | "proofExists"
      | "proofTimestamp"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProofAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorProof",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getProof", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "proofCreator",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proofExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proofTimestamp",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proofCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofTimestamp",
    data: BytesLike
  ): Result;
}

export namespace ProofAnchoredEvent {
  export type InputTuple = [
    proofHash: BytesLike,
    creator: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proofHash: string,
    creator: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proofHash: string;
    creator: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofLayer extends BaseContract {
  connect(runner?: ContractRunner | null): ProofLayer;
  waitForDeployment(): Promise<this>;

  interface: ProofLayerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorProof: TypedContractMethod<
    [proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getProof: TypedContractMethod<
    [proofHash: BytesLike],
    [
      [boolean, string, bigint] & {
        exists: boolean;
        creator: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  proofCreator: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  proofExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  proofTimestamp: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorProof"
  ): TypedContractMethod<[proofHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [proofHash: BytesLike],
    [
      [boolean, string, bigint] & {
        exists: boolean;
        creator: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proofCreator"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "proofExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proofTimestamp"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getEvent(
    key: "ProofAnchored"
  ): TypedContractEvent<
    ProofAnchoredEvent.InputTuple,
    ProofAnchoredEvent.OutputTuple,
    ProofAnchoredEvent.OutputObject
  >;

  filters: {
    "ProofAnchored(bytes32,address,uint256)": TypedContractEvent<
      ProofAnchoredEvent.InputTuple,
      ProofAnchoredEvent.OutputTuple,
      ProofAnchoredEvent.OutputObject
    >;
    ProofAnchored: TypedContractEvent<
      ProofAnchoredEvent.InputTuple,
      ProofAnchoredEvent.OutputTuple,
      ProofAnchoredEvent.OutputObject
    >;
  };
}
